version: "3"
services:
  mariadb:
    image: "mariadb:10.2"
    restart: 'always'
    volumes:
      - db_data:/var/lib/mysql
      - db_conf:/etc/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
volumes:
  db_data:
  db_conf: